export default {
  'profissoes': [
    { value: '389', label: 'Administrador de Rede' },
    { value: '5', label: 'Administrador(a)' },
    { value: '405', label: 'Administrador(a) de Banco de Dados' },
    { value: '64', label: 'Administrador(a) de Empresas' },
    { value: '192', label: 'Administrador(a) de Recursos Humanos' },
    { value: '293', label: 'Administrador(a) Hospitalar' },
    { value: '188', label: 'Administradora de Serviços do Lar' },
    { value: '3', label: 'Advogado(a)' },
    { value: '410', label: 'Agente Ambiental' },
    { value: '32', label: 'Agricultor(a)' },
    { value: '102', label: 'Agrônomo(a)' },
    { value: '110', label: 'Agropecuarista' },
    { value: '278', label: 'Ajudante de Caminhão' },
    { value: '251', label: 'Ajudante de Composição' },
    { value: '254', label: 'Ajudante de Foguista' },
    { value: '253', label: 'Ajudante de Vidreiro' },
    { value: '130', label: 'Almoxarife' },
    { value: '285', label: 'Analista' },
    { value: '104', label: 'Analista Administrativo (a)' },
    { value: '66', label: 'Analista Contábil' },
    { value: '376', label: 'Analista de Administração de Pessoal' },
    { value: '244', label: 'Analista de Captação' },
    { value: '220', label: 'Analista de Contratos' },
    { value: '247', label: 'Analista de Controladoria' },
    { value: '71', label: 'Analista de Controle Interno' },
    { value: '23', label: 'Analista de Crédito' },
    { value: '16', label: 'Analista de Custos' },
    { value: '375', label: 'Analista de Departamento Pessoal' },
    { value: '401', label: 'Analista de Exportação' },
    { value: '237', label: 'Analista de Faturamento' },
    { value: '248', label: 'Analista de IT' },
    { value: '79', label: 'Analista de Laboratório' },
    { value: '213', label: 'Analista de Logística' },
    { value: '325', label: 'Analista de Marketing' },
    { value: '215', label: 'Analista de Negócios' },
    { value: '217', label: 'Analista de Orçamentos' },
    { value: '100', label: 'Analista de Organização e Métodos' },
    { value: '238', label: 'Analista de Pessoal' },
    { value: '113', label: 'Analista de Recursos Humanos' },
    { value: '406', label: 'Analista de Remuneração Senior' },
    { value: '36', label: 'Analista de Sistemas' },
    { value: '321', label: 'Analista de Suporte Administrativo' },
    { value: '304', label: 'Analista de Suporte Pleno' },
    { value: '363', label: 'Analista de Tecidos' },
    { value: '134', label: 'Analista de Vendas' },
    { value: '65', label: 'Analista Financeiro' },
    { value: '135', label: 'Analista Fiscal' },
    { value: '245', label: 'Analista Senior de Previdência Privada' },
    { value: '208', label: 'Analista Tributária' },
    { value: '277', label: 'Apicultor(a)' },
    { value: '96', label: 'Aposentado(a)' },
    { value: '190', label: 'Armador de Pesca' },
    { value: '126', label: 'Arquiteto(a)' },
    { value: '123', label: 'Artesão(ã)' },
    { value: '18', label: 'Assistente Administrativo' },
    { value: '408', label: 'Assistente Comercial' },
    { value: '326', label: 'Assistente Contábil' },
    { value: '232', label: 'Assistente de Contas' },
    { value: '10', label: 'Assistente de Departamento Pessoal' },
    { value: '55', label: 'Assistente de Escritório' },
    { value: '59', label: 'Assistente de Faturamento' },
    { value: '236', label: 'Assistente de Gerencia de R.H.' },
    { value: '182', label: 'Assistente de Hotelaria Hospitalar' },
    { value: '85', label: 'Assistente de Planejamento' },
    { value: '402', label: 'Assistente de Processo' },
    { value: '317', label: 'Assistente de Produção' },
    { value: '60', label: 'Assistente de Recursos Humanos' },
    { value: '360', label: 'Assistente de Suprimentos' },
    { value: '56', label: 'Assistente Financeiro' },
    { value: '61', label: 'Assistente Jurídico' },
    { value: '48', label: 'Assistente Social' },
    { value: '283', label: 'Assistente Técnico Operacional' },
    { value: '193', label: 'Atendente' },
    { value: '398', label: 'Ator' },
    { value: '397', label: 'Atriz' },
    { value: '118', label: 'Auditor(a)' },
    { value: '209', label: 'Auditor(a) Fiscal' },
    { value: '171', label: 'Autônomo(a)' },
    { value: '199', label: 'Aux. de Serviços Gerais' },
    { value: '274', label: 'Auxiliar Acadêmico' },
    { value: '17', label: 'Auxiliar Administrativo' },
    { value: '12', label: 'Auxiliar Contábil' },
    { value: '255', label: 'Auxiliar de Compras' },
    { value: '334', label: 'Auxiliar de Cozinha' },
    { value: '381', label: 'Auxiliar de Departamento de Crédito' },
    { value: '380', label: 'Auxiliar de Departamento Financeiro' },
    { value: '365', label: 'Auxiliar de Departamento Fiscal' },
    { value: '187', label: 'Auxiliar de eletricista' },
    { value: '181', label: 'Auxiliar de Enfermagem' },
    { value: '94', label: 'Auxiliar de Escritório' },
    { value: '83', label: 'Auxiliar de Inspeção de Qualidade' },
    { value: '275', label: 'Auxiliar de Laboratório' },
    { value: '97', label: 'Auxiliar de Produção' },
    { value: '257', label: 'Auxiliar de Registro de Saúde' },
    { value: '6', label: 'Auxiliar de RH' },
    { value: '261', label: 'Auxiliar de Serviços' },
    { value: '84', label: 'Auxiliar Financeiro' },
    { value: '250', label: 'Auxiliar Operacional' },
    { value: '52', label: 'Auxiliar Técnico' },
    { value: '98', label: 'Avicultor( a )' },
    { value: '266', label: 'Bailarina (o)' },
    { value: '29', label: 'Bancário(a)' },
    { value: '354', label: 'Biólogo(a)' },
    { value: '90', label: 'Biomédico (a)' },
    { value: '386', label: 'Cabeleireiro(a)' },
    { value: '189', label: 'Caminhoneiro (a)' },
    { value: '286', label: 'carregador' },
    { value: '22', label: 'Catador(a)' },
    { value: '249', label: 'Catraqueiro' },
    { value: '307', label: 'Chefe da Secretaria de Expediente' },
    { value: '328', label: 'Chefe de Recursos Humanos' },
    { value: '115', label: 'Chefe de Serviços de Transporte' },
    { value: '30', label: 'Cirurgião(ã) Dentista' },
    { value: '409', label: 'Citricultor(a)' },
    { value: '125', label: 'Coletor(a) de Material Reciclável' },
    { value: '15', label: 'Comerciante' },
    { value: '50', label: 'Comerciário(a)' },
    { value: '68', label: 'Comprador(a)' },
    { value: '175', label: 'Comunicador(a) Social' },
    { value: '366', label: 'Condutor(a) Autônomo(a)' },
    { value: '89', label: 'Condutor(a) Escolar' },
    { value: '374', label: 'Conferente' },
    { value: '289', label: 'construtor' },
    { value: '191', label: 'Consultor(a) Administrativo' },
    { value: '184', label: 'Consultor(a) de Vendas' },
    { value: '9', label: 'Contabilista' },
    { value: '49', label: 'Contador(a)' },
    { value: '336', label: 'Contramestre' },
    { value: '70', label: 'Controller' },
    { value: '210', label: 'Coordenador(a)' },
    { value: '67', label: 'Coordenador(a) Administrativo Pessoal' },
    { value: '211', label: 'Coordenador(a) de Atendimento' },
    { value: '219', label: 'Coordenador(a) de Controladoria' },
    { value: '200', label: 'Coordenador(a) de Controle de Qualidade' },
    { value: '72', label: 'Coordenador(a) de Controle Interno' },
    { value: '359', label: 'Coordenador(a) de Engenharia Industrial' },
    { value: '404', label: 'Coordenador(a) de Exportação' },
    { value: '316', label: 'Coordenador(a) de Impostos' },
    { value: '77', label: 'Coordenador(a) de Instrumentos' },
    { value: '295', label: 'Coordenador(a) de Manutenção' },
    { value: '131', label: 'Coordenador(a) de Produção' },
    { value: '310', label: 'Coordenador(a) de Projetos' },
    { value: '395', label: 'Coordenador(a) de Recursos Humanos' },
    { value: '212', label: 'Coordenador(a) de Suprimentos' },
    { value: '197', label: 'Coordenador(a) de Transportes' },
    { value: '327', label: 'Coordenador(a) de Vendas' },
    { value: '370', label: 'Coordenador(a) Pedagógico(a)' },
    { value: '264', label: 'Coreógrafo' },
    { value: '225', label: 'Corretor(a) de Imóveis' },
    { value: '88', label: 'Corretor(a) de Seguros' },
    { value: '19', label: 'Costureiro(a)' },
    { value: '333', label: 'Cozinheiro(a)' },
    { value: '223', label: 'Cronoanalista' },
    { value: '332', label: 'Cuidador(a) de idoso' },
    { value: '265', label: 'Dançarina' },
    { value: '227', label: 'Delegado' },
    { value: '25', label: 'Dentista' },
    { value: '344', label: 'Desenvolvedor de Arte' },
    { value: '345', label: 'Desenvolvedor de Produtos Texteis' },
    { value: '367', label: 'Despachante' },
    { value: '353', label: 'Digitador(a)' },
    { value: '226', label: 'Diretor' },
    { value: '243', label: 'Diretor (a) Executivo (a)' },
    { value: '262', label: 'Diretor de Escola' },
    { value: '218', label: 'Diretor de Recursos Humanos' },
    { value: '378', label: 'Diretor(a) de Assuntos Técnicos' },
    { value: '319', label: 'Diretor(a) de Criação' },
    { value: '320', label: 'Diretor(a) de Produções' },
    { value: '329', label: 'Diretor(a) de Relações Públicas' },
    { value: '379', label: 'Diretor(a) de Relações Públicas e Sociais' },
    { value: '288', label: 'Do lar' },
    { value: '45', label: 'Economista' },
    { value: '74', label: 'Eletricista' },
    { value: '47', label: 'Eletricitário' },
    { value: '202', label: 'Embalador(a)' },
    { value: '185', label: 'Embalador(a) de Produtos' },
    { value: '124', label: 'Empregada Doméstica' },
    { value: '87', label: 'Empresário(a)' },
    { value: '42', label: 'Empresário(a) Rural' },
    { value: '234', label: 'Encarregado Automotivo' },
    { value: '235', label: 'Encarregado de Controladoria' },
    { value: '207', label: 'Encarregado(a)' },
    { value: '318', label: 'Encarregado(a) de Mídia' },
    { value: '26', label: 'Enfermeiro(a)' },
    { value: '1', label: 'Engenheiro(a)' },
    { value: '368', label: 'Engenheiro(a) Administrador(a)' },
    { value: '44', label: 'Engenheiro(a) Agrônomo(a)' },
    { value: '93', label: 'Engenheiro(a) Civil' },
    { value: '169', label: 'Engenheiro(a) de Alimentos' },
    { value: '400', label: 'Engenheiro(a) de Desenvolvimento Ambiental' },
    { value: '315', label: 'Engenheiro(a) de Segurança do Trabalho' },
    { value: '299', label: 'Engenheiro(a) Eletricista' },
    { value: '172', label: 'Engenheiro(a) Florestal' },
    { value: '168', label: 'Engenheiro(a) Mecânico' },
    { value: '308', label: 'Engenheiro(a) Naval' },
    { value: '312', label: 'Engenheiro(a) Químico(a)' },
    { value: '372', label: 'Escrevente Técnico Judiciário' },
    { value: '229', label: 'Escrituraria' },
    { value: '11', label: 'Escriturario(a)' },
    { value: '399', label: 'Especialista em Banco de Dados' },
    { value: '260', label: 'Estudante' },
    { value: '14', label: 'Farmacêutica(o)' },
    { value: '362', label: 'Faturista' },
    { value: '291', label: 'faxineira (o)' },
    { value: '127', label: 'Ferramenteiro' },
    { value: '323', label: 'Ferroviário' },
    { value: '27', label: 'Fisioterapeuta' },
    { value: '305', label: 'Floricultor(a)' },
    { value: '196', label: 'Fotógrafo(a)' },
    { value: '174', label: 'Funcionário(a) Público(a)' },
    { value: '292', label: 'funileiro' },
    { value: '313', label: 'Geógrafo(a)' },
    { value: '330', label: 'Geólogo(a)' },
    { value: '373', label: 'Gerente' },
    { value: '69', label: 'Gerente de Área' },
    { value: '382', label: 'Gerente de Contabilidade' },
    { value: '119', label: 'Gerente de Crédito e Cobrança' },
    { value: '411', label: 'Gerente de Faturamento' },
    { value: '120', label: 'Gerente de Recursos Humanos' },
    { value: '117', label: 'Gerente de Serviços de Transporte' },
    { value: '306', label: 'Gerente de Sistemas' },
    { value: '350', label: 'Gerente de Tecnologa da Informação' },
    { value: '246', label: 'Gerente de Tributário' },
    { value: '177', label: 'Gerente de Vendas' },
    { value: '114', label: 'Gerente de Vendas Distribuidores' },
    { value: '233', label: 'Gerente Departamento de Compra' },
    { value: '230', label: 'Gerente Financeiro' },
    { value: '394', label: 'Gerente Operacional' },
    { value: '133', label: 'Gerente Regional de Vendas' },
    { value: '111', label: 'Gestor(a) de Logística' },
    { value: '314', label: 'Gestor(a) de Negócios' },
    { value: '86', label: 'Gestor(a) de Projetos' },
    { value: '324', label: 'Gestor(a) Financeiro' },
    { value: '335', label: 'Impressor' },
    { value: '51', label: 'Industriário(a)' },
    { value: '128', label: 'Inspetor de Qualidade' },
    { value: '73', label: 'Instrumentista' },
    { value: '35', label: 'Intérprete' },
    { value: '287', label: 'Jardineiro' },
    { value: '4', label: 'Jornalista' },
    { value: '179', label: 'Lavrador(a)' },
    { value: '203', label: 'Líder de Embalagem' },
    { value: '204', label: 'Líder de Higienização' },
    { value: '107', label: 'Líder de Recepção' },
    { value: '392', label: 'Marceneiro' },
    { value: '297', label: 'Matemático(a)' },
    { value: '112', label: 'Mecânico' },
    { value: '270', label: 'Mecânico de Manutenção' },
    { value: '2', label: 'Medico(a)' },
    { value: '284', label: 'Médico(a) Pediátrico(a)' },
    { value: '33', label: 'Médico(a) Veterinário(a)' },
    { value: '53', label: 'Metalúrgico' },
    { value: '92', label: 'Militar' },
    { value: '388', label: 'Ministro Religioso' },
    { value: '20', label: 'Motorista' },
    { value: '43', label: 'Nutricionista' },
    { value: '91', label: 'Odontólogo (a)' },
    { value: '180', label: 'Oficial de Cartório' },
    { value: '369', label: 'Oficial de Justiça' },
    { value: '121', label: 'Oficial de Promotoria' },
    { value: '80', label: 'Oleiro(a)' },
    { value: '129', label: 'Operador (a)' },
    { value: '99', label: 'Operador (a) de Crédito Rural' },
    { value: '242', label: 'Operador de Caldeira' },
    { value: '343', label: 'Operador de Conicaleira' },
    { value: '341', label: 'Operador de Máquina' },
    { value: '342', label: 'Operador de Texturização' },
    { value: '201', label: 'Operador(a) de Caldeira' },
    { value: '78', label: 'Operador(a) de Forming' },
    { value: '351', label: 'Operador(a) de Imagem' },
    { value: '268', label: 'Operador(a) de Máquinas' },
    { value: '205', label: 'Orientador(a) Educacional' },
    { value: '40', label: 'Pecuarista' },
    { value: '263', label: 'Pedagogo(a)' },
    { value: '290', label: 'pedreiro' },
    { value: '252', label: 'Pedreiro Refratarista' },
    { value: '76', label: 'Planejador(a) de Manutenção' },
    { value: '95', label: 'Policial' },
    { value: '122', label: 'Policial Rodoviário' },
    { value: '331', label: 'Porteiro(a)' },
    { value: '198', label: 'Prensista' },
    { value: '267', label: 'Produtor (a)' },
    { value: '195', label: 'Produtor(a) Agropecuário' },
    { value: '41', label: 'Produtor(a) Rural' },
    { value: '24', label: 'Professor(a)' },
    { value: '356', label: 'Profissional Liberal' },
    { value: '38', label: 'Programador(a)' },
    { value: '46', label: 'Psicólogo(a)' },
    { value: '167', label: 'Publicitário(a)' },
    { value: '309', label: 'Químico(a)' },
    { value: '279', label: 'Reciclador(a)' },
    { value: '186', label: 'Reciclador(a) Ambiental Autônomo(a)' },
    { value: '340', label: 'Recobridor' },
    { value: '8', label: 'Representante Comercial' },
    { value: '358', label: 'Secretária Bilíngue' },
    { value: '216', label: 'Secretária de Diretoria' },
    { value: '280', label: 'Secretária Executiva' },
    { value: '7', label: 'Secretária(o)' },
    { value: '377', label: 'Securitário(a)' },
    { value: '387', label: 'Segurança' },
    { value: '108', label: 'Selecionador(a)' },
    { value: '391', label: 'Serralherio' },
    { value: '109', label: 'Servidor(a) Público(a)' },
    { value: '173', label: 'Sociólogo' },
    { value: '28', label: 'Supervisor(a)' },
    { value: '170', label: 'Supervisor(a) Administrativo' },
    { value: '407', label: 'Supervisor(a) de Adminstração de Pessoal' },
    { value: '396', label: 'Supervisor(a) de Atendimento' },
    { value: '221', label: 'Supervisor(a) de Compras' },
    { value: '222', label: 'Supervisor(a) de Custos' },
    { value: '303', label: 'Supervisor(a) de Elétrica e Instrumentação' },
    { value: '271', label: 'Supervisor(a) de Manufatura' },
    { value: '384', label: 'Supervisor(a) de Manutenção Industrial' },
    { value: '364', label: 'Supervisor(a) de Matéria-Prima' },
    { value: '116', label: 'Supervisor(a) de Operações' },
    { value: '403', label: 'Supervisor(a) de Produção' },
    { value: '241', label: 'Supervisor(a) de Recursos Humanos' },
    { value: '357', label: 'Supervisor(a) de Suprimentos' },
    { value: '206', label: 'Supervisor(a) de Tesouraria' },
    { value: '228', label: 'Supervisor(a) Financeiro' },
    { value: '383', label: 'Supervisor(a) Fiscal' },
    { value: '298', label: 'Tabelião' },
    { value: '31', label: 'Taxista' },
    { value: '338', label: 'Tecelão' },
    { value: '269', label: 'Técinico em Kaizen' },
    { value: '259', label: 'Técnica Agropecuária' },
    { value: '106', label: 'Técnico (a) Administrativo (a)' },
    { value: '258', label: 'Técnico de Métodos Gráficos' },
    { value: '224', label: 'Técnico de Operação de Usina Hidrelétrica' },
    { value: '346', label: 'Técnico de Tinturaria' },
    { value: '21', label: 'Técnico em Informática' },
    { value: '37', label: 'Técnico em Processamento' },
    { value: '101', label: 'Técnico(a) Agrícola' },
    { value: '281', label: 'Técnico(a) de Enfermagem' },
    { value: '183', label: 'Técnico(a) de Gesso' },
    { value: '273', label: 'Técnico(a) de Manutenção Elétrico' },
    { value: '296', label: 'Técnico(a) de Processos' },
    { value: '63', label: 'Técnico(a) em Contabilidade' },
    { value: '214', label: 'Técnico(a) em Edificações' },
    { value: '371', label: 'Técnico(a) em Eletrônica' },
    { value: '39', label: 'Técnico(a) em Informática' },
    { value: '178', label: 'Técnico(a) em Meio Ambiente' },
    { value: '82', label: 'Técnico(a) em Plástico' },
    { value: '282', label: 'Técnico(a) em Radiologia Médica' },
    { value: '132', label: 'Técnico(a) em Segurança do Trabalho' },
    { value: '355', label: 'Técnico(a) Mecânico(a)' },
    { value: '302', label: 'Técnico(a) Químico Industrial' },
    { value: '272', label: 'Tecnólogo do Produto Sênior' },
    { value: '231', label: 'Tecnólogo em Gestão Financeira' },
    { value: '256', label: 'Tecnólogo em Telecomunicações' },
    { value: '311', label: 'Tecnólogo(a)' },
    { value: '294', label: 'Tecnólogo(a) de Processo de Produção' },
    { value: '276', label: 'Tecnólogo(a) em Processamento de Dados' },
    { value: '81', label: 'Tecnólogo(a) Mecânico' },
    { value: '194', label: 'Telefonista' },
    { value: '337', label: 'Tintureiro' },
    { value: '393', label: 'Torneiro Mecânico' },
    { value: '34', label: 'Tradutor(a)' },
    { value: '339', label: 'Urdidor' },
    { value: '301', label: 'Vendedor(a)' },
    { value: '75', label: 'Vidreiro(a)' },
    { value: '300', label: 'Vigilante' },
    { value: '390', label: 'Web Designer' },
    { value: '54', label: 'Zootécnico(a)' }
  ]
}
